####
# This docker-compose file builds a container that runs the Quarkus application in JVM mode as well as the accompanying iris instance
# container used by the application.
#
# Before building the container image run:
#
# mvn package
#
# To build and run the network run:
#
# docker-compose  up
#
###

version: "3.8"
services:
  app:
    build:
      # Context set back to the project's root directory to allow docker to find the files in the
      # [target] directory, needed to create the quarkus app container. Not doing so can lead to
      # source not found or permission issues trying to access the files.
      context: src/main/docker
      dockerfile: Dockerfile.jvm
    ports:
      - "8080:8080"
  iris:
    image: quarkus-iris
    build: 
      context: src/main/docker/iris
    volumes:
      - ./:/irisrun/repo
    ports:
      - "52773:52773"
      - "1972:1972"
