version: "3.8"
services:
  quarkus-iris:
    build:
      # Context set back to the project's root directory to allow docker to find the files in the
      # [target] directory, needed to create the quarkus app container. Not doing so can lead to
      # source not found or permission issues trying to access the files.
      context: ./quarkus-iris-quickstart
      dockerfile: dockerfile
    ports:
      - "8080:8080"
  quarkus-iris-orm:
    build:
      context: ./quarkus-iris-orm-quickstart
      dockerfile: dockerfile
    ports:
      - "8081:8080"
  iris:
    image: iris-db
    build: 
      context: iris
    command: --check-caps false
    volumes:
      - ./:/irisrun/repo
    ports:
      - "52773:52773"
      - "1972:1972"
